### ISSUE TITLE
您好，请问您的学生/同事曲智宇 zhiyu qu拒不还我钱，一直说等他退学回国之后再说，我想了解一下他到底什么时候退学，是否真的有退学打算？

### ISSUE THREAD

**Issue by ghost** [wOOL/wool.github.io#1]

**Comment by quzhiyuhuanqian** [comment]
更新后续，这是什么意思，我为了要回我的钱还要再打几十万？是真的开销大还赤裸裸的诈骗？
![30B75BD6-4173-4545-AB79-CAD3C80980B7](https://user-images.githubusercontent.com/79713570/147829107-a9bc63d9-c04c-42b3-9cee-be9900ac3251.jpeg)
